### ISSUE TITLE
"Too many inputs" from AzureOpenAI

### ISSUE THREAD

**Issue by ryankmcintyre** [shivachittamuru/AndrewNg-OpenAI-Azure#2]
When using the VectorstoreIndexCreator in the langchain course (e.g. L4-QnA and L5-Evaluation), Azure returns an `InvalidRequestError` with the following message:

`Too many inputs. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.`

**Comment by shivachittamuru** [comment]
Added the following code to fix this issue:

`from langchain.embeddings import OpenAIEmbeddings`
`# embeddings = OpenAIEmbeddings() # this won't work because only 1 chunk is supported currently.`
`embeddings = OpenAIEmbeddings(model="text-embedding-ada-002", chunk_size=1)`
